# Generated by Django 4.0.6 on 2022-07-24 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField(max_length=250)),
                ('date', models.DateField(verbose_name='release date')),
                ('rating', models.CharField(choices=[('G', 'G'), ('P', 'PG'), ('T', 'PG-13'), ('R', 'R'), ('N', 'NC-17')], default='T', max_length=1)),
                ('genre', models.CharField(choices=[('D', 'Drama'), ('T', 'Thriller'), ('R', 'Romance'), ('A', 'Action'), ('C', 'Comedy'), ('H', 'Horror'), ('S', 'Science Fiction'), ('F', 'Fantacy')], default='A', max_length=1)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='view date')),
                ('time', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='E', max_length=1)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.movie')),
            ],
        ),
    ]
