# Generated by Django 4.0.6 on 2022-07-24 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ['-date']},
        ),
    ]
