# Generated by Django 4.0.6 on 2022-07-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='streams',
            field=models.ManyToManyField(to='main_app.stream'),
        ),
    ]
